//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.8689
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkflowAuthoring
{
    using System;
    using System.ComponentModel;
    using System.ComponentModel.Design;
    using System.Workflow.ComponentModel.Design;
    using System.Workflow.ComponentModel;
    using System.Workflow.ComponentModel.Serialization;
    using System.Workflow.ComponentModel.Compiler;
    using System.Drawing;
    using System.Collections;
    using System.Workflow.Activities;
    using System.Workflow.Runtime;
    
    
    public partial class StartRunbook : System.Workflow.Activities.SequentialWorkflowActivity
    {
        public static System.Workflow.ComponentModel.DependencyProperty StartRunbok_RunbookNameProperty = DependencyProperty.Register("StartRunbok_RunbookName", typeof(System.String), typeof(WorkflowAuthoring.StartRunbook));

        public string StartRunbok_RunbookName
        {
            get
            {
                return ((string)(base.GetValue(WorkflowAuthoring.StartRunbook.StartRunbok_RunbookNameProperty)));
            }
            set
            {
                base.SetValue(WorkflowAuthoring.StartRunbook.StartRunbok_RunbookNameProperty, value);
            }
        }
    }
}
